spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboard?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      maximum-pool-size: 20

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  refresh-exp: 2592000000
  access-exp: 3600000
  prefix: Bearer
  header: Authorization
  key: zxcpaslkdfjhoiuxcubjasdfyy891oiu3jknfasoidfyi89uysuoijvbwah7e987fiweojkfalmsdfhiowejufklsdafhj

server:
  port: 8080
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false